import type { Metadata } from "next";

import "./globals.css";
import { Orbitron } from "next/font/google";
import Providers from "@/components/Providers";
import Nav from "@/components/Nav";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Clodron Star ID - BETA",
  description: "Generated by create next app",
};

const font = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#ffecd8]">
      <body className={font.className}>
        <Providers>
          <Nav />
          {children}
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
